spring:
  rabbitmq:
    host: 106.15.73.154
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: simple